### ISSUE TITLE
ModuleNotFoundError: No module named 'app.api'

### ISSUE THREAD

**Issue by TheTh1nk3r** [XTeam-Wing/Vulcan#6]
root@301f1c62eca0:/opt/Vulcan# python3.7 Vulcan.py 
Traceback (most recent call last):
  File "Vulcan.py", line 4, in <module>
    from app.router import create_app
  File "/opt/Vulcan/app/router.py", line 6, in <module>
    from app.api.demo.demo import HelloWorld
ModuleNotFoundError: No module named 'app.api'

**Comment by Pa55w0rd** [comment]
同样的问题，没有app.api
